// lib/payments/razorpay.ts
// Secure Razorpay server integration and verification utilities.

import crypto from 'node:crypto';
import Razorpay from 'razorpay';

export interface RazorpayConfig {
  keyId: string;
  keySecret: string;
  webhookSecret?: string;
}

export function getRazorpayConfig(): RazorpayConfig | null {
  const keyId = process.env.RAZORPAY_KEY_ID || process.env.NEXT_PUBLIC_RAZORPAY_KEY_ID;
  const keySecret = process.env.RAZORPAY_KEY_SECRET;
  const webhookSecret = process.env.RAZORPAY_WEBHOOK_SECRET;

  if (!keyId || !keySecret) {
    return null;
  }

  return {
    keyId: keyId.trim(),
    keySecret: keySecret.trim(),
    webhookSecret: webhookSecret?.trim(),
  };
}

export function isRazorpayConfigured(): boolean {
  return getRazorpayConfig() !== null;
}

export function getRazorpayClient(): Razorpay | null {
  const config = getRazorpayConfig();
  if (!config) return null;

  return new Razorpay({
    key_id: config.keyId,
    key_secret: config.keySecret,
  });
}

/**
 * Validates the payment signature generated by Razorpay Checkout.
 * Signature format: HMAC_SHA256(order_id + "|" + payment_id, secret)
 */
export function verifyPaymentSignature(params: {
  orderId: string;
  paymentId: string;
  signature: string;
}): boolean {
  const config = getRazorpayConfig();
  if (!config) return false;

  try {
    const expectedSignature = crypto
      .createHmac('sha256', config.keySecret)
      .update(`${params.orderId}|${params.paymentId}`)
      .digest('hex');

    const expectedBuf = Buffer.from(expectedSignature, 'utf-8');
    const signatureBuf = Buffer.from(params.signature, 'utf-8');

    if (expectedBuf.length !== signatureBuf.length) {
      return false;
    }

    return crypto.timingSafeEqual(expectedBuf, signatureBuf);
  } catch {
    return false;
  }
}

/**
 * Validates a Razorpay webhook raw payload signature using RAZORPAY_WEBHOOK_SECRET.
 */
export function verifyWebhookSignature(rawBody: string, signature: string): boolean {
  const config = getRazorpayConfig();
  if (!config || !config.webhookSecret) return false;

  try {
    const expectedSignature = crypto
      .createHmac('sha256', config.webhookSecret)
      .update(rawBody)
      .digest('hex');

    const expectedBuf = Buffer.from(expectedSignature, 'utf-8');
    const signatureBuf = Buffer.from(signature, 'utf-8');

    if (expectedBuf.length !== signatureBuf.length) {
      return false;
    }

    return crypto.timingSafeEqual(expectedBuf, signatureBuf);
  } catch {
    return false;
  }
}
