import { createAdminClient } from '@/lib/supabase/admin';
import { createServerSupabaseClient } from '@/lib/supabase/server';
import type { BookDocument, BookPageDocument } from '@/lib/book/types';
import { toPublicBookDocument } from './public-book';
import { signedAssetUrl } from './asset-storage';

function pagesFromRows(rows: Array<Record<string, unknown>>): BookPageDocument[] {
  return rows.map((page) => ({
    pageNumber: Number(page.page_number),
    chapterIndex: Number(page.chapter_index || 0),
    title: typeof page.title === 'string' ? page.title : undefined,
    pageType: (page.page_type || 'illustrated_content') as BookPageDocument['pageType'],
    layout: (page.layout || 'standard') as BookPageDocument['layout'],
    blocks: Array.isArray(page.blocks) ? page.blocks : [],
  }));
}

function documentFromRows(book: Record<string, any>, pages: BookPageDocument[]): BookDocument {
  return {
    schemaVersion: 1,
    id: String(book.id),
    userId: String(book.user_id),
    title: String(book.title),
    subtitle: book.subtitle || undefined,
    bookType: book.book_type,
    language: book.language || 'English',
    style: book.style || 'Modern',
    pageCount: Number(book.page_count || pages.length),
    coverAssetId: book.cover_asset_id || undefined,
    coverUrl: book.cover_url || book.cover_image_url || undefined,
    blueprint: book.blueprint,
    versionNumber: Number(book.version_number || 1),
    isShared: Boolean(book.is_shared),
    shareToken: book.share_token || undefined,
    pages,
    createdAt: String(book.created_at),
    updatedAt: String(book.updated_at),
  };
}

export async function hydrateAssetUrls(book: BookDocument): Promise<BookDocument> {
  const assetIds = new Set<string>();
  if (book.coverAssetId) assetIds.add(book.coverAssetId);
  for (const page of book.pages) {
    for (const block of page.blocks) {
      if (block.assetId) assetIds.add(block.assetId);
    }
  }
  if (assetIds.size === 0) return book;

  const admin = createAdminClient();
  const { data: assets } = await admin
    .from('assets')
    .select('id, storage_path')
    .in('id', Array.from(assetIds));
  const urls = new Map<string, string>();
  await Promise.all((assets || []).map(async (asset) => {
    const url = await signedAssetUrl(asset.storage_path);
    if (url) urls.set(asset.id, url);
  }));

  return {
    ...book,
    coverUrl: (book.coverAssetId && urls.get(book.coverAssetId)) || book.coverUrl,
    pages: book.pages.map((page) => ({
      ...page,
      blocks: page.blocks.map((block) => ({
        ...block,
        url: block.assetId ? urls.get(block.assetId) || block.url : block.url,
      })),
    })),
  };
}

export async function getServerBook(id: string): Promise<BookDocument | null> {
  try {
    const supabase = createAdminClient();
    const { data: dbBook, error: bookError } = await supabase
      .from('books')
      .select('*')
      .eq('id', id)
      .maybeSingle();

    if (bookError || !dbBook) return null;

    // /book/[id] is the private authoring reader. Public readers must use the
    // opaque /shared/[token] route so an ID can never grant edit access.
    const sessionClient = await createServerSupabaseClient();
    const { data: { user } } = await sessionClient.auth.getUser();
    if (!user || user.id !== dbBook.user_id) return null;

    const { data: dbPages, error: pagesError } = await supabase
      .from('book_pages')
      .select('*')
      .eq('book_id', id)
      .order('page_number', { ascending: true });
    if (pagesError || !dbPages) return null;

    return await hydrateAssetUrls(documentFromRows(dbBook, pagesFromRows(dbPages)));
  } catch (err) {
    console.error('getServerBook error:', err);
    return null;
  }
}

export async function getServerSharedBook(token: string): Promise<BookDocument | null> {
  // Share tokens are UUIDs generated by Postgres. Reject arbitrary filter
  // expressions and never fall back to looking up a private book by its ID.
  const uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
  if (!uuidPattern.test(token)) return null;

  try {
    const supabase = createAdminClient();
    const { data: dbBook, error: bookError } = await supabase
      .from('books')
      .select('*')
      .eq('share_token', token)
      .eq('is_shared', true)
      .maybeSingle();

    if (bookError || !dbBook) return null;

    const { data: dbPages, error: pagesError } = await supabase
      .from('book_pages')
      .select('*')
      .eq('book_id', dbBook.id)
      .order('page_number', { ascending: true });
    if (pagesError || !dbPages || dbPages.length === 0) return null;

    const hydrated = await hydrateAssetUrls(documentFromRows(dbBook, pagesFromRows(dbPages)));
    return toPublicBookDocument({ ...hydrated, isShared: true });
  } catch (err) {
    console.error('getServerSharedBook error:', err);
    return null;
  }
}
